In [30]:
#Utilizo la libreria de Pandas
import pandas as pd

#Guarda los datos en un Data Frame llamdo dfCRE del archivo csv COLOMBIANOS_REGISTRADOS_EN_EL_EXTERIOR_20250403
dfCRE = pd.read_csv("COLOMBIANOS_REGISTRADOS_EN_EL_EXTERIOR_20250403.csv")

C:\Users\Edan\AppData\Local\Temp\ipykernel_51520\2109589165.py:5: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCRE = pd.read_csv("COLOMBIANOS_REGISTRADOS_EN_EL_EXTERIOR_20250403.csv")

In [31]:
#Muestra la cantidad de filas y columnas del data set
dfCRE.shape

(1672255, 17)

In [ ]:
#Metodo info() muestra la informacion de las columnas encabezado y el tipo de datos
dfCRE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1672255 entries, 0 to 1672254
Data columns (total 17 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   País                   1672255 non-null  object
 1   Código ISO país        1672255 non-null  object
 2   Ciudad de Residencia   1672255 non-null  object
 3   Oficina de registro    1672255 non-null  object
 4   Grupo edad             1672255 non-null  object
 5   Edad (años)            1672255 non-null  int64
 6   Área Conocimiento      1672255 non-null  object
 7   Sub Area Conocimiento  1672255 non-null  object
 8   Nivel Académico        1672255 non-null  object
 9   Estado civil           1672255 non-null  object
 10  Género                 1672255 non-null  object
 11  Etnia de la persona    1672255 non-null  object
 12  Estatura (CM)          1672255 non-null  object
 13  Ciudad de Nacimiento   1672255 non-null  object
 14  Localización           1672255 non-null  object
 15  Fecha de Registro      1672255 non-null  object
 16  Cantidad de personas   1672255 non-null  int64
dtypes: int64(2), object(15)
memory usage: 216.9+ MB

In [81]:
#Metodo value_counts los valores presentes en la columna país realiza el conteo de los valores con mas
#ocurrencias los muestra de orden decreciente en este caso muestra los 5 primeros con mas ocurrencias
#y los 5 ultimos con menos ocurrencias
dfCRE.País.value_counts()

País
ESTADOS UNIDOS    492422
ESPA�A            429353
VENEZUELA         223027
ECUADOR            89177
CANADA             53926
                   ...
MAURITANIA             1
BOTSUANA               1
GUINEA-BISSAU          1
BUTAN                  1
ZAMBIA                 1
Name: count, Length: 194, dtype: int64

In [34]:
#Muestra los encabezados, las 5 primeras filas y las 5 ultimas filas
dfCRE

,País,Código ISO país,Ciudad de Residencia,Oficina de registro,Grupo edad,Edad (años),Área Conocimiento,Sub Area Conocimiento,Nivel Académico,Estado civil,Género,Etnia de la persona,Estatura (CM),Ciudad de Nacimiento,Localización,Fecha de Registro,Cantidad de personas
0,MEXICO,MEX,NUEVO LEON/MONTERREY,C. MEXICO,ADOLESCENTE,16,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/ATLANTICO/BARRANQUILLA,"(23.634501, -102.552784)",2017-07,1
1,ALBANIA,ALB,TIRANE/FACESH,C. ROMA,DESCONOCIDO,-1,NO INDICA,NO INDICA,BACHILLERATO,DESCONOCIDO,FEMENINO,SIN ETNIA REGISTRADA,-1,COLOMBIA/ANTIOQUIA/ITAGUI,"(41.153332, 20.168331)",2015-10,1
2,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,NINGUNA,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-02,1
3,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-02,1
4,ECUADOR,ECU,PICHINCHA/QUITO,C. QUITO,ADULTO,52,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/CALDAS/SUPIA,"(-1.831239, -78.183406)",2016-08,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1672250,ESTADOS UNIDOS,USA,CALIFORNIA/ORANGEVALE,C. SAN FRANCISCO,ADULTO,56,CIENCIAS DE LA SALUD,ODONTOLOG�A,NO INDICA,CASADO,FEMENINO,NINGUNA,-1,COLOMBIA/VALLE DEL CAUCA/RESTREPO,"(37.09024, -95.712891)",2016-04,1
1672251,ESPA�A,ESP,MADRID/MADRID,C. MADRID,ADULTO,36,NINGUNA,NINGUNA,BACHILLERATO,CASADO,MASCULINO,AFRODESCENDIENTE,166,COLOMBIA/VALLE DEL CAUCA/PALMIRA,"(40.463667, -3.74922)",2014-11,1
1672252,ESTADOS UNIDOS,USA,NEW JERSEY/ENGLEWOOD,C. NEWARK,ADULTO MAYOR,62,NINGUNA,NINGUNA,NO INDICA,DIVORCIADO,FEMENINO,OTRO,-1,COLOMBIA/RISARALDA/APIA,"(37.09024, -95.712891)",2017-08,1
1672253,ESPA�A,ESP,MURCIA/JUMILLA,C. VALENCIA ESP,ADULTO MAYOR,63,NINGUNA,NINGUNA,NO INDICA,CASADO,MASCULINO,NINGUNA,-1,COLOMBIA/CALDAS/RISARALDA,"(40.463667, -3.74922)",2021-08,1
1672254,VENEZUELA,VEN,ZULIA/MARACAIBO,C. MARACAIBO,ADULTO,36,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,VENEZUELA/ZULIA/MARACAIBO,"(6.42375, -66.58973)",2018-08,3

In [35]:
#Metodo columns muestra el encabezado de las columnas
dfCRE.columns

Index(['País', 'Código ISO país', 'Ciudad de Residencia',
       'Oficina de registro', 'Grupo edad', 'Edad (años)', 'Área Conocimiento',
       'Sub Area Conocimiento', 'Nivel Académico', 'Estado civil', 'Género',
       'Etnia de la persona', 'Estatura (CM)', 'Ciudad de Nacimiento',
       'Localización', 'Fecha de Registro', 'Cantidad de personas'],
      dtype='object')

In [79]:
#Metodo head() muestra el encabezado de las columnas con el numero de las primeras 
#filas indicadas, inicia desde 0 con el numero indicado de filas 
dfCRE.head(20)

,País,Código ISO país,Ciudad de Residencia,Oficina de registro,Grupo edad,Edad (años),Área Conocimiento,Sub Area Conocimiento,Nivel Académico,Estado civil,Género,Etnia de la persona,Estatura (CM),Ciudad de Nacimiento,Localización,Fecha de Registro,Cantidad de personas
0,MEXICO,MEX,NUEVO LEON/MONTERREY,C. MEXICO,ADOLESCENTE,16,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/ATLANTICO/BARRANQUILLA,"(23.634501, -102.552784)",2017-07,1
1,ALBANIA,ALB,TIRANE/FACESH,C. ROMA,DESCONOCIDO,-1,NO INDICA,NO INDICA,BACHILLERATO,DESCONOCIDO,FEMENINO,SIN ETNIA REGISTRADA,-1,COLOMBIA/ANTIOQUIA/ITAGUI,"(41.153332, 20.168331)",2015-10,1
2,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,NINGUNA,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-02,1
3,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-02,1
4,ECUADOR,ECU,PICHINCHA/QUITO,C. QUITO,ADULTO,52,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/CALDAS/SUPIA,"(-1.831239, -78.183406)",2016-08,1
5,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2024-07,1
6,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,MASCULINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2023-03,1
7,CURA�AO,CUW,CURA�AO/WILLEMSTAD,C. WILLEMSTAD,ADULTO,46,NINGUNA,NINGUNA,BACHILLERATO,UNION_LIBRE,FEMENINO,OTRO,-1,COLOMBIA/ANTIOQUIA/ITAGUI,"(12.16957, -68.990021)",2023-03,1
8,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,13,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/HUILA/NEIVA,"(51.165691, 10.451526)",2021-10,1
9,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,13,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/ANTIOQUIA/MEDELLIN,"(51.165691, 10.451526)",2022-06,1
10,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,13,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2022-04,1
11,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,13,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,FRANCIA/ILE-DE-FRANCE/SAINT-MAUR-DES-FOSSES,"(51.165691, 10.451526)",2022-05,1
12,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,14,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,NINGUNA,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2022-06,1
13,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,14,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2021-12,1
14,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,14,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2022-06,1
15,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,14,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,COLOMBIA/QUINDIO/ARMENIA,"(51.165691, 10.451526)",2021-08,1
16,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,15,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,MASCULINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2023-01,1
17,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,15,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,MASCULINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-10,1
18,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,15,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,MASCULINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN-PANKOW,"(51.165691, 10.451526)",2024-09,1
19,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,15,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,ALEMANIA/THURINGEN/WEIMAR,"(51.165691, 10.451526)",2021-08,1

In [78]:
#Metodo tail() muestra el encabezado de las columnas con las ultimas filas indicadas
#inicia desde la ultima fila con el numero indicado.
dfCRE.tail(10)

,País,Código ISO país,Ciudad de Residencia,Oficina de registro,Grupo edad,Edad (años),Área Conocimiento,Sub Area Conocimiento,Nivel Académico,Estado civil,Género,Etnia de la persona,Estatura (CM),Ciudad de Nacimiento,Localización,Fecha de Registro,Cantidad de personas
1672245,COSTA RICA,CRI,HEREDIA/BARVA,C. SAN JOSE,ADULTO,31,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,NINGUNA,-1,COLOMBIA/VALLE DEL CAUCA/BUENAVENTURA,"(9.748917, -83.753428)",2022-08,1
1672246,NUEVA ZELANDA,NZL,AUCKLAND/AUCKLAND,C. AUCKLAND,ADULTO,38,CIENCIAS SOCIALES Y HUMANAS,PSICOLOG�A Y AFINES,NO INDICA,UNION_LIBRE,FEMENINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(-40.900557, 174.885971)",2018-10,1
1672247,ESPA�A,ESP,ANDALUCIA/GRANADA,C. SEVILLA,ADULTO,51,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/ANTIOQUIA/ITAGUI,"(40.463667, -3.74922)",2020-07,1
1672248,ESPA�A,ESP,MADRID/COSLADA,C. MADRID,ADULTO JOVEN,20,NINGUNA,NINGUNA,PRIMARIA,UNION_LIBRE,FEMENINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOT� DC,"(40.463667, -3.74922)",2023-10,1
1672249,FEDERACION DE RUSIA,RUS,BELGOROD/BELGOROD,C. MOSCU,ADULTO JOVEN,23,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/CUNDINAMARCA/BOGOTA D.C.,"(61.52401, 105.318756)",2022-02,1
1672250,ESTADOS UNIDOS,USA,CALIFORNIA/ORANGEVALE,C. SAN FRANCISCO,ADULTO,56,CIENCIAS DE LA SALUD,ODONTOLOG�A,NO INDICA,CASADO,FEMENINO,NINGUNA,-1,COLOMBIA/VALLE DEL CAUCA/RESTREPO,"(37.09024, -95.712891)",2016-04,1
1672251,ESPA�A,ESP,MADRID/MADRID,C. MADRID,ADULTO,36,NINGUNA,NINGUNA,BACHILLERATO,CASADO,MASCULINO,AFRODESCENDIENTE,166,COLOMBIA/VALLE DEL CAUCA/PALMIRA,"(40.463667, -3.74922)",2014-11,1
1672252,ESTADOS UNIDOS,USA,NEW JERSEY/ENGLEWOOD,C. NEWARK,ADULTO MAYOR,62,NINGUNA,NINGUNA,NO INDICA,DIVORCIADO,FEMENINO,OTRO,-1,COLOMBIA/RISARALDA/APIA,"(37.09024, -95.712891)",2017-08,1
1672253,ESPA�A,ESP,MURCIA/JUMILLA,C. VALENCIA ESP,ADULTO MAYOR,63,NINGUNA,NINGUNA,NO INDICA,CASADO,MASCULINO,NINGUNA,-1,COLOMBIA/CALDAS/RISARALDA,"(40.463667, -3.74922)",2021-08,1
1672254,VENEZUELA,VEN,ZULIA/MARACAIBO,C. MARACAIBO,ADULTO,36,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,VENEZUELA/ZULIA/MARACAIBO,"(6.42375, -66.58973)",2018-08,3

In [77]:
#Metodo loc muestra las filas indicadas
dfCRE.loc[[100000, 200000, 800000]]

,País,Código ISO país,Ciudad de Residencia,Oficina de registro,Grupo edad,Edad (años),Área Conocimiento,Sub Area Conocimiento,Nivel Académico,Estado civil,Género,Etnia de la persona,Estatura (CM),Ciudad de Nacimiento,Localización,Fecha de Registro,Cantidad de personas
100000,ECUADOR,ECU,PICHINCHA/QUITO,C. QUITO,ADULTO,40,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/ANTIOQUIA/MEDELLIN,"(-1.831239, -78.183406)",2021-06,1
200000,ESTADOS UNIDOS,USA,NEW JERSEY/NEWARK,C. NEWARK,ADULTO,52,NINGUNA,NINGUNA,NO INDICA,CASADO,FEMENINO,NINGUNA,-1,COLOMBIA/LA GUAJIRA/RIOHACHA,"(37.09024, -95.712891)",2017-02,1
800000,ESPA�A,ESP,CATALU�A/HOSPITALET,C. BARCELONA,ADULTO JOVEN,23,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/QUINDIO/ARMENIA,"(40.463667, -3.74922)",2024-12,1

In [76]:
#Metodo unique muestra los valores unicos (sin duplicados) de la columna indicada
dfCRE["Nivel Académico"].unique()

array(['NO INDICA', 'BACHILLERATO', 'PRIMARIA', 'PREGRADO - PROFESIONAL',
       'NINGUNO', 'POSTGRADO - MAESTRIA', 'POSTGRADO - DOCTORADO',
       'PREGRADO - TECNOL�GICO', 'PREGRADO - T�CNICO PROFESIONAL',
       'POSTGRADO - ESPECIALIZACI�N', '(NO REGISTRA)', 'SIN PROFESI�N',
       'ESPECIALIZACI�N', 'TECNOL�GICA', 'UNIVERSITARIO',
       'T�CNICA PROFESIONAL', 'MAESTRIA'], dtype=object)

In [75]:
#Metodo describe muestra una descripcion estadistica de la columna indicada
dfCRE["Nivel Académico"].describe()

count       1672255
unique           17
top       NO INDICA
freq         757189
Name: Nivel Académico, dtype: object

In [74]:
#Muestra los valores con la cantidad de ocurrencias en orden decreciente condicionado con la
#columna Genero FEMENINO y columna Nivel Académico
dfCRE[dfCRE['Género'] == 'FEMENINO'][['Género', "Nivel Académico"]].value_counts()

Género    Nivel Académico
FEMENINO  NO INDICA                         414765
          BACHILLERATO                      209928
          PREGRADO - PROFESIONAL            111488
          PRIMARIA                           55552
          PREGRADO - T�CNICO PROFESIONAL     42596
          POSTGRADO - MAESTRIA               23425
          PREGRADO - TECNOL�GICO             19898
          NINGUNO                            17276
          POSTGRADO - ESPECIALIZACI�N        14856
          POSTGRADO - DOCTORADO               4083
          (NO REGISTRA)                        397
          SIN PROFESI�N                        130
          ESPECIALIZACI�N                        2
          TECNOL�GICA                            1
Name: count, dtype: int64

In [73]:
#Muestra los valores con la cantidad de ocurrencias en orden decreciente condicionado con la
#columna Genero FEMENINO y columna País
dfCRE[dfCRE['Género'] == 'FEMENINO'][['Género', "País"]].value_counts()

Género    País
FEMENINO  ESTADOS UNIDOS                  269888
          ESPA�A                          246522
          VENEZUELA                       119954
          ECUADOR                          44554
          CANADA                           28690
                                           ...
          SAN VICENTE Y LAS GRANADINAS         1
          TOGO                                 1
          UZBEKISTAN                           1
          YEMEN                                1
          ZAMBIA                               1
Name: count, Length: 184, dtype: int64

In [72]:
#Muestra los valores con la cantidad de ocurrencias en orden decreciente condicionado con la
#columna Nivel Académico PREGRADO - PROFESIONAL, ademas de las columnas Género, Nivel Académico y Ciudad de Nacimiento
dfCRE[dfCRE['Nivel Académico'] == 'PREGRADO - PROFESIONAL'][['Género', "Nivel Académico", "Ciudad de Nacimiento"]].value_counts()

Género       Nivel Académico         Ciudad de Nacimiento
FEMENINO     PREGRADO - PROFESIONAL  COLOMBIA/CUNDINAMARCA/BOGOTA     22129
MASCULINO    PREGRADO - PROFESIONAL  COLOMBIA/CUNDINAMARCA/BOGOTA     16602
FEMENINO     PREGRADO - PROFESIONAL  COLOMBIA/VALLE DEL CAUCA/CALI     9886
                                     (NO REGISTRA)                     9049
                                     COLOMBIA/ANTIOQUIA/MEDELLIN       7979
                                                                      ...
DESCONOCIDO  PREGRADO - PROFESIONAL  COLOMBIA/BOYACA/SOCOTA               1
                                     COLOMBIA/BOYACA/SANTANA              1
                                     COLOMBIA/BOYACA/RONDON               1
                                     COLOMBIA/BOYACA/DUITAMA              1
                                     COLOMBIA/BOYACA/CUCAITA              1
Name: count, Length: 5296, dtype: int64

In [84]:
#Metodo unique muestra los valores unicos (sin duplicados) de la columna indicada
dfCRE["Grupo edad"].unique()

array(['ADOLESCENTE', 'DESCONOCIDO', 'ADULTO', 'ADULTO JOVEN',
       'ADULTO MAYOR', 'INFANTE', 'PRIMERA INFANCIA'], dtype=object)

In [83]:
#Metodo describe muestra una descripcion estadistica de la columna indicada
dfCRE["Fecha de Registro"].describe()

count     1672255
unique        148
top       2018-03
freq        31492
Name: Fecha de Registro, dtype: object

In [82]:
#Metodo unique muestra los valores unicos (sin duplicados) de la columna indicada
dfCRE["Fecha de Registro"].unique()

array(['2017-07', '2015-10', '2023-02', '2016-08', '2024-07', '2023-03',
       '2021-10', '2022-06', '2022-04', '2022-05', '2021-12', '2021-08',
       '2023-01', '2023-10', '2024-09', '2022-03', '2017-08', '2023-11',
       '2024-04', '2016-05', '2022-09', '2023-04', '2025-03', '2024-06',
       '2014-03', '2024-02', '2017-12', '2021-06', '2021-05', '2014-02',
       '2014-05', '2018-05', '2023-12', '2024-03', '2022-08', '2013-04',
       '2023-09', '2021-09', '2023-07', '2021-07', '2024-01', '2022-01',
       '2019-11', '2014-08', '2013-11', '2022-10', '2022-07', '2023-05',
       '2015-08', '2022-02', '2015-12', '2020-07', '2022-11', '2017-05',
       '2024-05', '2024-08', '2018-09', '2021-11', '2013-10', '2020-08',
       '2018-11', '2014-01', '2017-02', '2020-09', '2016-03', '2018-04',
       '2017-03', '2013-12', '2023-06', '2020-10', '2017-11', '2015-09',
       '2018-02', '2015-06', '2018-01', '2023-08', '2015-02', '2013-09',
       '2015-11', '2017-04', '2014-06', '2015-05', '2018-08', '2017-06',
       '2015-07', '2018-03', '2016-06', '2014-04', '2020-01', '2014-12',
       '2016-02', '2013-06', '2017-10', '2015-04', '2013-08', '2015-03',
       '2024-11', '2020-11', '2013-03', '2014-09', '2013-07', '2020-03',
       '2018-12', '2019-03', '2014-10', '2019-10', '2021-03', '2016-01',
       '2019-09', '2019-08', '2021-04', '2017-09', '2016-11', '2017-01',
       '2019-01', '2019-07', '2025-01', '2021-02', '2016-09', '2014-07',
       '2016-04', '2019-05', '2021-01', '2016-12', '2020-05', '2020-12',
       '2016-07', '2019-04', '2018-06', '2020-02', '2022-12', '2018-07',
       '2020-06', '2020-04', '2018-10', '2019-06', '2016-10', '2019-12',
       '2013-05', '2019-02', '2025-02', '1900-01', '2024-10', '2015-01',
       '2024-12', '2014-11', '2013-02', '2025-04'], dtype=object)